Repository babkiniaa/SCAS, pull requests merged in 2024-10, with the labels that each got.

#35 Появилось скачивание
  backend/agent/src/main/java/org/github/babkiniaa/scas/controller/ChallengeController.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/dto/ProjectDto.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/dto/ReportDto.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/entity/Project.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/mapper/ProjectMapper.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/mapper/ReportMapper.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/repository/ProjectRepository.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/service/ProjectService.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/textReader/GitStatus.java
  backend/manager/pom.xml
Labels: Перенос

#38 Добавился checkstyle
  backend/agent/src/main/java/org/github/babkiniaa/scas/analysis/StaticAnalysis.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/controller/ChallengeController.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/dto/ReportIdDto.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/service/ReportService.java
Labels: Перенос

#37 Добавился owasp
  backend/agent/src/main/java/org/github/babkiniaa/scas/analysis/StaticAnalysis.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/controller/ChallengeController.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/dto/ReportIdDto.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/service/ReportService.java
Labels: Перенос

#39 добавился pmd
  backend/agent/src/main/java/org/github/babkiniaa/scas/analysis/StaticAnalysis.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/controller/ChallengeController.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/service/ReportService.java
Labels: Перенос

#40 Добавился spotbugs
  backend/agent/src/main/java/org/github/babkiniaa/scas/analysis/BinAnalysis.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/controller/ChallengeController.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/service/ReportService.java
Labels: Перенос

#43 Future/issue 41
  frontend/src/pages/CreateProjectPage.vue
  frontend/src/router/routes.js
  frontend/src/services/projectServices.js
Labels: front

#53 Агент готов
  backend/agent/pom.xml
  backend/agent/src/main/java/org/github/babkiniaa/scas/AgentRun.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/analysis/BinAnalysis.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/analysis/StaticAnalysis.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/parsers/CheckStyleParser.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/parsers/DependencyCheckParser.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/parsers/Parser.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/parsers/PmdParser.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/parsers/SpotBugsParser.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/parsers/XmlParser.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/textReader/DeleteFile.java
  backend/agent/src/main/java/org/github/babkiniaa/scas/textReader/GitStatus.java
  backend/manager/pom.xml
  backend/manager/src/main/java/org/github/babkiniaa/scas/App.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/DemoApplication.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/config/Config.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/controllers/AdminController.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/controllers/AuthController.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/controllers/PasswordController.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/controllers/UserController.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/dto/ChangePasswordDto.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/dto/LoginDto.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/dto/RegistrationDto.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/entity/Role.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/entity/Token.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/entity/User.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/exception/PasswordException.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/mappers/UserMapper.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/repository/RoleRepository.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/repository/TokenRepository.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/repository/UserRepository.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/service/EmailService.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/service/TokenService.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/service/UserDetailsServiceImpl.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/service/UserService.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/validatros/Password.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/validatros/PasswordValidator.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/validatros/UniqueEmail.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/validatros/UniqueEmailValidator.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/validatros/UniqueLogin.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/validatros/UniqueLoginValidator.java
  backend/manager/src/main/resources/application.yaml
  backend/manager/src/test/java/org/github/babkiniaa/scas/AppTest.java
  backend/pom.xml
Labels: agent

#58 поменял путь
  backend/agent/src/main/java/org/github/babkiniaa/scas/analysis/BinAnalysis.java
  backend/manager/src/main/java/org/github/babkiniaa/scas/controllers/ChallengeController.java
Labels: bug

#65 Сделал все в 1
  backend/manager/src/main/java/org/github/babkiniaa/scas/controllers/ChallengeController.java
  backend/master/src/main/java/org/github/babkiniaa/scas/dto/ProjectDto.java
  backend/master/src/main/java/org/github/babkiniaa/scas/dto/ReportIdDto.java
Labels: Перенос
